# Generated by Django 5.1.5 on 2025-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_userid_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
